name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # заміни на твою основну гілку

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Клон репозиторію
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Встановлення Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Встановлення залежностей
      - name: Install dependencies
        run: npm install

      # 4. Збірка проекту
      - name: Build React app
        run: npm run build

      # 5. Деплой на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PAT_TOKEN }}  # Твій Personal Access Token
          publish_dir: ./build
